window.__justep.__ResourceEngine.loadCss([{url: '/system/components/pc.addon.min.css', include: '$model/system/components/justep/cellLayout/css/cellLayout,$model/system/components/justep/pagerLimitSelect/css/pagerLimitSelect,$model/system/components/justep/widgets/css/widgets,$model/system/components/justep/smartContainer/css/smartContainer,$model/system/components/justep/absoluteLayout/css/absoluteLayout,$model/system/components/justep/pagerBar/css/pagerBar'},{url: '/system/components/comp.min.css', include: '$model/system/components/justep/row/css/row,$model/system/components/justep/attachment/css/attachment,$model/system/components/justep/barcode/css/barcodeImage,$model/system/components/bootstrap/form/css/form,$model/system/components/justep/panel/css/panel,$model/system/components/bootstrap/accordion/css/accordion,$model/system/components/justep/common/css/scrollable,$model/system/components/bootstrap/pager/css/pager,$model/system/components/justep/scrollView/css/scrollView,$model/system/components/justep/input/css/datePickerPC,$model/system/components/bootstrap/navs/css/navs,$model/system/components/justep/contents/css/contents,$model/system/components/justep/popMenu/css/popMenu,$model/system/components/justep/lib/css/icons,$model/system/components/justep/titleBar/css/titleBar,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/justep/dialog/css/dialog,$model/system/components/justep/messageDialog/css/messageDialog,$model/system/components/bootstrap/navbar/css/navbar,$model/system/components/justep/toolBar/css/toolBar,$model/system/components/justep/popOver/css/popOver,$model/system/components/justep/loadingBar/loadingBar,$model/system/components/justep/input/css/datePicker,$model/system/components/justep/dataTables/css/dataTables,$model/system/components/bootstrap/dialog/css/dialog,$model/system/components/justep/wing/css/wing,$model/system/components/bootstrap/scrollSpy/css/scrollSpy,$model/system/components/justep/menu/css/menu,$model/system/components/justep/numberSelect/css/numberList,$model/system/components/justep/list/css/list,$model/system/components/bootstrap/carousel/css/carousel,$model/system/components/bootstrap/dropdown/css/dropdown,$model/system/components/justep/common/css/forms,$model/system/components/justep/bar/css/bar,$model/system/components/bootstrap/tabs/css/tabs,$model/system/components/bootstrap/pagination/css/pagination'},{url: '/system/components/bootstrap.min.css', include: '$model/system/components/bootstrap/lib/css/bootstrap,$model/system/components/bootstrap/lib/css/bootstrap-theme'}]);window.__justep.__ResourceEngine.loadJs(['/system/components/pc.addon.min.js','/system/components/comp2.min.js','/system/components/comp.min.js','/system/common.min.js','/system/core.min.js']);define(function(require){
require('$model/UI2/system/components/justep/labelEdit/labelEdit');
require('$model/UI2/system/components/justep/pagerLimitSelect/pagerLimitSelect');
require('$model/UI2/system/components/justep/loadingBar/loadingBar');
require('$model/UI2/system/components/justep/row/row');
require('$model/UI2/system/components/justep/pagerBar/pagerBar');
require('$model/UI2/system/components/justep/select/select');
require('$model/UI2/system/components/justep/list/list');
require('$model/UI2/system/components/justep/windowDialog/windowDialog');
require('$model/UI2/system/components/justep/model/model');
require('$model/UI2/system/components/justep/window/window');
require('$model/UI2/system/components/justep/data/data');
require('$model/UI2/system/components/bootstrap/pagination/pagination');
require('$model/UI2/system/components/justep/button/button');
require('$model/UI2/system/components/justep/output/output');
require('$model/UI2/system/components/justep/toolBar/toolBar');
var __parent1=require('$model/UI2/system/lib/base/modelBase'); 
var __parent0=require('$model/UI2/Print/mainActivity'); 
var __result = __parent1._extend(__parent0).extend({
	constructor:function(contextUrl){
	this.__sysParam='true';
	this.__contextUrl=contextUrl;
	this.__id='__baseID__';
	this.__cid='cmMVNzi';
	this._flag_='04cf469fd432a0ac5ac7360bdb71a6c2';
	this.callParent(contextUrl);
 var __Data__ = require("$UI/system/components/justep/data/data");new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":false,"defCols":{"class_attr":{"define":"class_attr","label":"课程属性","name":"class_attr","relation":"class_attr","type":"String"},"class_name":{"define":"class_name","label":"课程名","name":"class_name","relation":"class_name","type":"String"},"credit":{"define":"credit","label":"学分","name":"credit","relation":"credit","rules":{"number":true},"type":"Double"},"deservedCredit":{"define":"deservedCredit","label":"实得学分","name":"deservedCredit","relation":"deservedCredit","rules":{"number":true},"type":"Double"},"fID":{"define":"fID","label":"fid","name":"fID","relation":"fID","rules":{"calculate":"justep.UUID.createUUID()","integer":true},"type":"Integer"},"grade":{"define":"grade","label":"成绩","name":"grade","relation":"grade","rules":{"number":true},"type":"Double"},"point":{"define":"point","label":"绩点","name":"point","relation":"point","rules":{"number":true},"type":"Double"},"time":{"define":"time","label":"时间","name":"time","relation":"time","rules":{"date":true},"type":"Date"}},"directDelete":true,"events":{"onCustomRefresh":"mainDataCustomRefresh","onCustomSave":"mainDataCustomSave"},"idColumn":"fID","limit":20,"xid":"mainData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"class_attr":{"define":"class_attr","label":"课程属性","name":"class_attr","relation":"class_attr","type":"String"},"class_name":{"define":"class_name","label":"课程名","name":"class_name","relation":"class_name","type":"String"},"credit":{"define":"credit","label":"学分","name":"credit","relation":"credit","rules":{"number":true},"type":"Double"},"deservedCredit":{"define":"deservedCredit","label":"实得学分","name":"deservedCredit","relation":"deservedCredit","rules":{"number":true},"type":"Double"},"fID":{"define":"fID","label":"fID","name":"fID","relation":"fID","rules":{"integer":true},"type":"Integer"},"grade":{"define":"grade","label":"成绩","name":"grade","relation":"grade","rules":{"number":true},"type":"Double"},"point":{"define":"point","label":"绩点","name":"point","relation":"point","rules":{"number":true},"type":"Double"},"time":{"define":"time","label":"时间","name":"time","relation":"time","rules":{"date":true},"type":"Date"}},"directDelete":false,"events":{"onCustomRefresh":"allDataCustomRefresh","onCustomSave":"allDataCustomSave"},"idColumn":"fID","limit":100,"xid":"allData"});
 new __Data__(this,{"autoLoad":true,"confirmDelete":true,"confirmRefresh":true,"defCols":{"id":{"define":"id","label":"id","name":"id","relation":"id","type":"String"},"userName":{"define":"userName","label":"name","name":"userName","relation":"userName","type":"String"}},"directDelete":false,"events":{"onCustomRefresh":"userCustomRefresh"},"idColumn":"id","limit":20,"xid":"user"});
}}); 
return __result;});
